version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eduhub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.production
    networks:
      - eduhub-network

networks:
  eduhub-network:
    driver: bridge 